/*
DROP TABLE IF EXISTS "PITCHER_RANKINGS";
DROP TABLE IF EXISTS "PITCHER_STATS";
DROP TABLE IF EXISTS "PITCHER_BIO";
DROP TABLE IF EXISTS "HITTER_RANKINGS";
DROP TABLE IF EXISTS "HITTER_BIO";
DROP TABLE IF EXISTS "HITTER_STATS";
*/

CREATE TABLE "PITCHER_RANKINGS"(
	"PLAYER_RANK" INT,
	"PLAYERPOS" VARCHAR,
	"OVERALL" INT,
	"BEST" INT,
	"WORST" INT,
	"RANK_AVG" DECIMAL,
	"STD_DEV" DECIMAL,
	"ADP" DECIMAL,
	"VS_ADP" VARCHAR,
	"NOTES" VARCHAR,
	"PLAYER" VARCHAR
);

CREATE TABLE "PITCHER_STATS"(
	"SEASON" VARCHAR,
	"TEAM" VARCHAR,
	"GAMES" VARCHAR,
	"GS" INT,
	"W" INT,
	"L" INT,
	"SV" INT,
	"BS" INT,
	"HD" INT,
	"CG" INT,
	"SHO" INT,
	"IP" DECIMAL,
	"H" INT,
	"R" INT,
	"ER" INT,
	"HR" INT,
	"BB" INT,
	"BB_PCT" DECIMAL,
	"SO" INT,
	"K_PCT" DECIMAL,
	"ERA" DECIMAL,
	"WHIP" DECIMAL,
	"PLAYER" VARCHAR
);

CREATE TABLE "PITCHER_BIO"(
	"PLAYER" VARCHAR NOT NUll,
	"AGE" INT NOT NUll, 
	"COLLEGE" VARCHAR,
	"BATS" VARCHAR NOT NUll,
	"THROWS" VARCHAR NOT NUll
);

CREATE TABLE "HITTER_RANKINGS"(
	"PLAYER_RANK" INT,
	"PLAYERPOS" VARCHAR,
	"OVERALL" INT,
	"BEST" INT,
	"WORST" INT,
	"RANK_AVG" DECIMAL,
	"STD_DEV" DECIMAL,
	"ADP" DECIMAL,
	"VS_ADP" VARCHAR,
	"NOTES" VARCHAR,
	"PLAYER" VARCHAR
);

CREATE TABLE "HITTER_BIO"(
	"PLAYER" VARCHAR NOT NUll,
	"AGE" INT NOT NUll, 
	"COLLEGE" VARCHAR,
	"BATS" VARCHAR NOT NUll,
	"THROWS" VARCHAR NOT NUll
);

CREATE TABLE "HITTER_STATS"(
	"SEASON" VARCHAR,
	"TEAM" VARCHAR,
	"GAMES" INT,
	"AB" INT,
	"R" INT,
	"H" INT,
	"SECOND_BASE" INT,
	"THIRD_BASE" INT,
	"HR" INT,
	"RBI" INT,
	"BB" INT,
	"HBP" INT,
	"SF" INT,
	"SO" INT,
	"SB" INT,
	"CS" INT, 
	"BATTING_AVG" DECIMAL,
	"OBP" DECIMAL,
	"SLG" DECIMAL,
	"OPS" DECIMAL,
	"BABIP" DECIMAL,
	"PLAYER" VARCHAR
);

/*
ALTER TABLE "HITTER_BIO" ADD PRIMARY KEY  ("PLAYER");
ALTER TABLE "HITTER_RANKINGS" ADD PRIMARY KEY ("PLAYER");
ALTER TABLE "HITTER_STATS" ADD PRIMARY KEY ("PLAYER","SEASON","TEAM");
ALTER TABLE "PITCHER_STATS" ADD PRIMARY KEY ("PLAYER","SEASON","TEAM");
ALTER TABLE "PITCHER_BIO" ADD PRIMARY KEY ("PLAYER");
ALTER TABLE "PITCHER_RANKINGS" ADD PRIMARY KEY ("PLAYER");
*/