SELECT * FROM "PITCHER_STATS";

-- DELETE FROM "PITCHER_STATS"
-- WHERE "PITCHER_STATS"."SEASON" LIKE '%Totals%';

SELECT * FROM "PITCHER_BIO";

SELECT * FROM "PITCHER_RANKINGS";

-- DELETE FROM "PITCHER_RANKINGS" 
-- WHERE "PLAYER_RANK" > 50;


SELECT * FROM "HITTER_RANKINGS";

SELECT * FROM "HITTER_RANKINGS" 
WHERE "PLAYER_RANK" <= 50;

SELECT * FROM "HITTER_BIO";

SELECT * FROM "HITTER_STATS";

-- DELETE FROM "HITTER_STATS"
-- WHERE "HITTER_STATS"."SEASON" LIKE '%Totals%';