/*
DROP TABLE IF EXISTS PITCHER_RANKINGS;
DROP TABLE IF EXISTS "PITCHER_STATS";
DROP TABLE IF EXISTS "PITCHER_BIO";
DROP TABLE IF EXISTS hitters;
DROP TABLE IF EXISTS hitter_bio;
DROP TABLE IF EXISTS hitter_stats;
*/

CREATE TABLE PITCHER_RANKINGS(
	PLAYER_RANK INT,
	PLAYERPOS VARCHAR,
	OVERALL INT,
	BEST INT,
	WORST INT,
	RANK_AVG DECIMAL,
	STD_DEV DECIMAL,
	ADP DECIMAL,
	VS_ADP DECIMAL,
	NOTES VARCHAR,
	PLAYER VARCHAR
);

CREATE TABLE "PITCHER_STATS"(
	"SEASON" VARCHAR,
	"TEAM" VARCHAR,
	"GAMES" VARCHAR,
	"GS" INT,
	"W" INT,
	"L" INT,
	"SV" INT,
	"BS" INT,
	"HD" INT,
	"CG" INT,
	"SHO" INT,
	"IP" DECIMAL,
	"H" INT,
	"R" INT,
	"ER" INT,
	"HR" INT,
	"BB" INT,
	"BB_PCT" DECIMAL,
	"SO" INT,
	"K_PCT" DECIMAL,
	"ERA" DECIMAL,
	"WHIP" DECIMAL,
	"PLAYER" VARCHAR
);

CREATE TABLE "PITCHER_BIO"(
	"PLAYER" VARCHAR NOT NUll,
	"AGE" INT NOT NUll, 
	"COLLEGE" VARCHAR,
	"BATS" VARCHAR NOT NUll,
	"THROWS" VARCHAR NOT NUll
);

CREATE TABLE "HITTER_RANKINGS"(
	"PLAYER_RANK" INT,
	"PLAYERPOS" VARCHAR,
	"OVERALL" INT,
	"BEST" INT,
	"WORST" INT,
	"RANK_AVG" DECIMAL,
	"STD_DEV" DECIMAL,
	"ADP" DECIMAL,
	"VS_ADP" VARCHAR,
	"NOTES" VARCHAR,
	"PLAYER" VARCHAR
);

CREATE TABLE "HITTER_BIO"(
	"PLAYER" VARCHAR NOT NUll,
	"AGE" INT NOT NUll, 
	"COLLEGE" VARCHAR,
	"BATS" VARCHAR NOT NUll,
	"THROWS" VARCHAR NOT NUll
);

CREATE TABLE "HITTER_STATS"(
	"SEASON" VARCHAR,
	"TEAM" VARCHAR,
	"GAMES" INT,
	"AB" INT,
	"R" INT,
	"H" INT,
	"SECOND_BASE" INT,
	"THIRD_BASE" INT,
	"HR" INT,
	"RBI" INT,
	"BB" INT,
	"HBP" INT,
	"SF" INT,
	"SO" INT,
	"SB" INT,
	"CS" INT, 
	"BATTING_AVG" DECIMAL,
	"OBP" DECIMAL,
	"SLG" DECIMAL,
	"OPS" DECIMAL,
	"BABIP" DECIMAL,
	"PLAYER" VARCHAR
);

/*
ALTER TABLE hitter_bio add primary key Name
ALTER TABLE hitters add primary key PLAYER
ALTER TABLE hitter_stats add primary key Name
ALTER TABLE pitcher_stats add primary key Name
ALTER TABLE pitcher_bio add primary key Name
ALTER TABLE pitcher add primary key PLAYER
*/